name: iran_safar
description: Iran Safar - Flutter scaffold (offline + online modes)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.0
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^6.0.4
  shared_preferences: ^2.3.2
  shared_preferences_web: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/geo/iran_full_provinces_cities.geo.json
    - assets/data/places_full.json
    - assets/images/places/

# NOTE: Ensure these packages are in dependencies:
# provider, shared_preferences
